name: develop-push-workflow
on:
  push:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer:v2
          php-version: '7.4'

      - name: Install proyect dependencies
        run: composer install

      - name: Run validate Test
        uses: ./vendor/bin/phpunit -c phpunit.xml
