name: develop-push-workflow
on:
  push:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop
        uses: actions/checkout@v2

      - name: Set up PHP
        user: shivammathur/setup-phpv2
        with:
          tools: composer:v2
          php-version: '8'
